// GENERATED by design-system. Run from the project root:
//   npx vitest run --config .design/system/guards/vitest.config.ts
// Optional: GUARD_SCAN_DIRS="src,app,components" also scans project source for off-scale radii and off-palette colors.
import { defineConfig } from 'vitest/config'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))

export default defineConfig({
  test: { root: here, include: ['*.test.ts'], environment: 'node' },
})
